INHERIT: utils/mkdocs-base.yml

site_name: 香山开源处理器设计文档
repo_url: https://github.com/OpenXiangShan/XiangShan-Design-Doc
repo_name: XiangShan-Design-Doc

nav:
  - 前端:
    - 取指目标队列: frontend/FTQ/FTQ.md
    - 取指令单元:
      - 整体设计: frontend/IFU/IFU.md
      - 预译码器: frontend/IFU/PreDecoder.md
    - 指令缓存:
      - 整体设计: frontend/ICache/ICache.md
      - MainPipe: frontend/ICache/MainPipe.md
      - IPrefetchPipe: frontend/ICache/IPrefetchPipe.md
      - WayLookup: frontend/ICache/WayLookup.md
      - MissUnit: frontend/ICache/MissUnit.md
      - Replacer: frontend/ICache/Replacer.md
      - CtrlUnit: frontend/ICache/CtrlUnit.md
  - 访存:
    - 内存管理单元 MMU: 
      - memblock/MMU/index.md
      - L1TLB: memblock/MMU/L1TLB.md
      - Repeater: memblock/MMU/Repeater.md
      - L2TLB:
        - memblock/MMU/L2TLB/index.md
        - Page Cache: memblock/MMU/L2TLB/PageCache.md
        - Page Table Walker: memblock/MMU/L2TLB/PTW.md
        - Last Level Page Table Walker: memblock/MMU/L2TLB/LLPTW.md
        - Hypervisor Page Table Walker: memblock/MMU/L2TLB/HPTW.md
        - Miss Queue: memblock/MMU/L2TLB/MissQueue.md
        - Prefetcher: memblock/MMU/L2TLB/Prefetcher.md
      - PMP & PMA: memblock/MMU/PMP-PMA.md
