name: build via pandoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openxiangshan/docs-utils:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: build
        env:
          HOME: /root
        run: |
          git config --global --add safe.directory $(pwd)
          make pdf
          make pdf TWOSIDE=1

      - name: Upload built pdf
        uses: actions/upload-artifact@v4
        with:
          name: xiangshan-design-doc-pdf
          path: |
            xiangshan-design-doc-zh.pdf
            xiangshan-design-doc-zh-twoside.pdf
